services:
  app:
    image: ashleykza/comfyui:latest
    ports:
      - "8188:3001"
    environment:
      EXTRA_ARGS: "--cpu"
      PRELOAD_MODELS: "[]"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "app"
      my.stacker.scope: "project"
      my.stacker.service: "comfyui"

networks:
  app-network:
    driver: bridge

