name: screego

deploy:
  target: server
  server:
    host: ${DEPLOY_HOST}
    user: root
    ssh_key: ${BASE_PATH}/stacker-project-test

services:
  screego:
    image: screego/server:1
    ports:
      - "5050:5050"
      - "3478:3478"
      - "50000-50200:50000-50200/udp"
    environment:
      SCREEGO_EXTERNAL_IP: "${DEPLOY_HOST}"
      SCREEGO_TURN_PORT_RANGE: "50000:50200"
      SCREEGO_AUTH_MODE: "none"
