time-format %T
date-format %d/%b/%Y
log-format COMBINED
real-time-html true
daemonize false
addr 0.0.0.0
port 7890
origin *
ws-url ws://localhost:7890
output /srv/report/index.html
log-file /srv/logs/access.log
