FROM alpine:3.19

RUN apk add --no-cache \
    curl \
    wget \
    httpie \
    jq \
    yq \
    net-tools \
    iputils \
    bind-tools \
    openssl \
    ca-certificates

ENTRYPOINT ["sleep", "infinity"]
