name: wikijs
version: "2.0.300"

app:
  type: custom
  image: ghcr.io/requarks/wiki:2
  ports:
    - "3000:3000"
  environment:
    DB_TYPE: postgres
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_NAME: wikijs
    DB_USER: wikijs
    DB_PASS: ${WIKIJS_DATABASE_PASSWORD}
    PGSSLMODE: disable

services:
  - name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: ${WIKIJS_DATABASE_PASSWORD}
    volumes:
      - "wikijs-postgres:/var/lib/postgresql/data"


install:
  inputs:
    domain: wiki.try.direct
    wikijs-database-password: ""

config_contract:
  services:
    app:
      fields:
        DB_HOST:
          mutability: editable
        DB_NAME:
          mutability: editable
        DB_PASS:
          mutability: editable
        DB_PORT:
          mutability: editable
        DB_TYPE:
          mutability: editable
        DB_USER:
          mutability: editable
        PGSSLMODE:
          mutability: editable
    postgres:
      fields:
        POSTGRES_DB:
          mutability: editable
        POSTGRES_PASSWORD:
          mutability: generated
          type: alphanumeric
          length: 32
          display: password
        POSTGRES_USER:
          mutability: editable
      volumes:
        wikijs-postgres:
          mutability: generated
