#!/bin/bash
# Hanko migrations - run manually after deploy
# The config.yaml is generated by generate-secrets.sh in the pre_build hook
set -e

echo "Hanko: migrations must be run manually on the server after deploy."
echo "See hanko-HOWTO.md for instructions."
