services:
  app:
    image: kong/kong:3.9.1
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjA0MzkwODAwLCJleHAiOjE5NzAwNTQyMDB9.dpB6Gi6uF-7s17fQ-z84Dzwsrxtd9J5Fi9Eiup5W3NM"
      DASHBOARD_PASSWORD: "f9beb1dd0eaac090a95588eaa149cae5"
      DASHBOARD_USERNAME: "supabase"
      JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/kong.yml"
      KONG_DNS_NOT_FOUND_TTL: "1"
      KONG_DNS_ORDER: "LAST,A,CNAME"
      KONG_NGINX_PROXY_PROXY_BUFFERS: "64 160k"
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: "160k"
      KONG_PLUGINS: "request-transformer,cors,key-auth,acl,basic-auth,request-termination,ip-restriction,post-function,correlation-id"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout combined"
      SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2MDQzOTA4MDAsImV4cCI6MTk3MDA1NDIwMH0.3g2bMmfRyu-kquVFoH2Pp-yCJdDrFhpcWnqNsrlvM7Y"
      SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjA0MzkwODAwLCJleHAiOjE5NzAwNTQyMDB9.dpB6Gi6uF-7s17fQ-z84Dzwsrxtd9J5Fi9Eiup5W3NM"
      SUPABASE_PUBLIC_URL: "http://localhost:8000"
      SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2MDQzOTA4MDAsImV4cCI6MTk3MDA1NDIwMH0.3g2bMmfRyu-kquVFoH2Pp-yCJdDrFhpcWnqNsrlvM7Y"
    volumes:
      - "./kong.yml:/usr/local/kong/kong.yml"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "app"
      my.stacker.scope: "project"
      my.stacker.service: "supabase"

  db:
    image: supabase/postgres:17.6.1.136
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      AUTHENTICATOR_PASSWORD: "913496e4675d253ad5ba601a50387f405707649bb34d21692bbdf9762044035c"
      JWT_EXP: "3600"
      JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "913496e4675d253ad5ba601a50387f405707649bb34d21692bbdf9762044035c"
      SUPABASE_AUTH_ADMIN_PASSWORD: "913496e4675d253ad5ba601a50387f405707649bb34d21692bbdf9762044035c"
      SUPABASE_FUNCTIONS_ADMIN_PASSWORD: "913496e4675d253ad5ba601a50387f405707649bb34d21692bbdf9762044035c"
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "./volumes/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:ro"
      - "./volumes/db/jwt.sql:/docker-entrypoint-initdb.d/init-scripts/99-jwt.sql:ro"
    healthcheck:
      test: "CMD pg_isready -U postgres && psql -U postgres -c \"SELECT 1 FROM pg_roles WHERE rolname='authenticator' AND rolpassword IS NOT NULL\" | grep -q 1"
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "db"
      my.stacker.scope: "project"
      my.stacker.service: "db"

  studio:
    image: supabase/studio:2026.06.03-sha-0bca601
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      HOSTNAME: "0.0.0.0"
      JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
      PGRST_DB_SCHEMAS: "public,storage,graphql_public"
      PG_META_CRYPTO_KEY: "2e46436bee4602457a1aaa506fae50c80742ab668e5e71465a4a15953bd2d150"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PASSWORD: "913496e4675d253ad5ba601a50387f405707649bb34d21692bbdf9762044035c"
      POSTGRES_PORT: "5432"
      STUDIO_PG_META_URL: "http://meta:8080"
      SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjA0MzkwODAwLCJleHAiOjE5NzAwNTQyMDB9.dpB6Gi6uF-7s17fQ-z84Dzwsrxtd9J5Fi9Eiup5W3NM"
      SUPABASE_PUBLIC_URL: "http://localhost:8000"
      SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2MDQzOTA4MDAsImV4cCI6MTk3MDA1NDIwMH0.3g2bMmfRyu-kquVFoH2Pp-yCJdDrFhpcWnqNsrlvM7Y"
      SUPABASE_URL: "http://app:8000"
    volumes:
      - "studio_snippets:/app/snippets"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "studio"
      my.stacker.scope: "project"
      my.stacker.service: "studio"

  auth:
    image: supabase/gotrue:v2.189.0
    environment:
      API_EXTERNAL_URL: "http://localhost:8000"
      GOTRUE_API_HOST: "0.0.0.0"
      GOTRUE_API_PORT: "9999"
      GOTRUE_DB_DATABASE_URL: "postgres://supabase_auth_admin:913496e4675d253ad5ba601a50387f405707649bb34d21692bbdf9762044035c@db:5432/postgres"
      GOTRUE_DB_DRIVER: "postgres"
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_JWT_ADMIN_ROLES: "service_role"
      GOTRUE_JWT_AUD: "authenticated"
      GOTRUE_JWT_DEFAULT_GROUP_NAME: "authenticated"
      GOTRUE_JWT_EXP: "3600"
      GOTRUE_JWT_ISSUER: "http://localhost:8000/auth/v1"
      GOTRUE_JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
      GOTRUE_MAILER_AUTOCONFIRM: "false"
      GOTRUE_SITE_URL: "http://localhost:3000"
      GOTRUE_SMTP_ADMIN_EMAIL: "admin@example.com"
      GOTRUE_SMTP_HOST: "supabase-mail"
      GOTRUE_SMTP_PASS: "fake_mail_password"
      GOTRUE_SMTP_PORT: "2500"
      GOTRUE_SMTP_SENDER_NAME: "fake_sender"
      GOTRUE_SMTP_USER: "fake_mail_user"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "auth"
      my.stacker.scope: "project"
      my.stacker.service: "auth"

  rest:
    image: postgrest/postgrest:v14.12
    environment:
      PGRST_APP_SETTINGS_JWT_EXP: "3600"
      PGRST_APP_SETTINGS_JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
      PGRST_DB_ANON_ROLE: "anon"
      PGRST_DB_EXTRA_SEARCH_PATH: "public"
      PGRST_DB_MAX_ROWS: "1000"
      PGRST_DB_SCHEMAS: "public,storage,graphql_public"
      PGRST_DB_URI: "postgres://authenticator:913496e4675d253ad5ba601a50387f405707649bb34d21692bbdf9762044035c@db:5432/postgres"
      PGRST_JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "rest"
      my.stacker.scope: "project"
      my.stacker.service: "rest"

  realtime:
    image: supabase/realtime:v2.102.3
    environment:
      APP_NAME: "realtime"
      DB_ENC_KEY: "supabaserealtime"
      DB_HOST: "db"
      DB_NAME: "postgres"
      DB_PASSWORD: "913496e4675d253ad5ba601a50387f405707649bb34d21692bbdf9762044035c"
      DB_PORT: "5432"
      DB_USER: "supabase_admin"
      DISABLE_HEALTHCHECK_LOGGING: "true"
      JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
      METRICS_JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
      PORT: "4000"
      RUN_JANITOR: "true"
      SECRET_KEY_BASE: "743a9a648b4d8d0650f182ce1a886355fca35cff2d019e7669cac25ba78e6e60"
      SEED_SELF_HOST: "true"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "realtime"
      my.stacker.scope: "project"
      my.stacker.service: "realtime"

  storage:
    image: supabase/storage-api:v1.60.4
    environment:
      ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjA0MzkwODAwLCJleHAiOjE5NzAwNTQyMDB9.dpB6Gi6uF-7s17fQ-z84Dzwsrxtd9J5Fi9Eiup5W3NM"
      DATABASE_URL: "postgres://supabase_storage_admin:913496e4675d253ad5ba601a50387f405707649bb34d21692bbdf9762044035c@db:5432/postgres"
      ENABLE_IMAGE_TRANSFORMATION: "true"
      FILE_SIZE_LIMIT: "52428800"
      FILE_STORAGE_BACKEND_PATH: "/var/lib/storage"
      IMGPROXY_URL: "http://imgproxy:5001"
      JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
      PGRST_JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
      POSTGREST_URL: "http://rest:3000"
      REGION: "stub"
      SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2MDQzOTA4MDAsImV4cCI6MTk3MDA1NDIwMH0.3g2bMmfRyu-kquVFoH2Pp-yCJdDrFhpcWnqNsrlvM7Y"
      STORAGE_BACKEND: "file"
      STORAGE_PUBLIC_URL: "http://localhost:8000"
    volumes:
      - "storage_data:/var/lib/storage"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "storage"
      my.stacker.scope: "project"
      my.stacker.service: "storage"

  imgproxy:
    image: darthsim/imgproxy:v3.30.1
    environment:
      IMGPROXY_BIND: ":5001"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/"
      IMGPROXY_USE_ETAG: "true"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "imgproxy"
      my.stacker.scope: "project"
      my.stacker.service: "imgproxy"

  meta:
    image: supabase/postgres-meta:v0.96.6
    environment:
      CRYPTO_KEY: "2e46436bee4602457a1aaa506fae50c80742ab668e5e71465a4a15953bd2d150"
      PG_META_DB_HOST: "db"
      PG_META_DB_NAME: "postgres"
      PG_META_DB_PASSWORD: "913496e4675d253ad5ba601a50387f405707649bb34d21692bbdf9762044035c"
      PG_META_DB_PORT: "5432"
      PG_META_DB_USER: "postgres"
      PG_META_PORT: "8080"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "meta"
      my.stacker.scope: "project"
      my.stacker.service: "meta"

  functions:
    image: supabase/edge-runtime:v1.74.0
    environment:
      JWT_SECRET: "28b35c7dd1625924794145fa6eb5d234203df2c6c4ec522bfeccac7d92b83af6"
      SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjA0MzkwODAwLCJleHAiOjE5NzAwNTQyMDB9.dpB6Gi6uF-7s17fQ-z84Dzwsrxtd9J5Fi9Eiup5W3NM"
      SUPABASE_PUBLIC_URL: "http://localhost:8000"
      SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2MDQzOTA4MDAsImV4cCI6MTk3MDA1NDIwMH0.3g2bMmfRyu-kquVFoH2Pp-yCJdDrFhpcWnqNsrlvM7Y"
      SUPABASE_URL: "http://app:8000"
      VERIFY_JWT: "false"
    volumes:
      - "./volumes/functions:/home/deno/functions:ro"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "functions"
      my.stacker.scope: "project"
      my.stacker.service: "functions"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  studio_snippets:
  storage_data:

