name: paperless-ngx
version: 2.11.0
organization: null
project:
  identity: paperless-ngx
app:
  type: python
  path: .
  dockerfile: null
  image: ghcr.io/paperless-ngx/paperless-ngx:latest
  build: null
  ports:
  - 8000:8000
  volumes:
  - paperless_data:/usr/src/paperless/data
  - paperless_media:/usr/src/paperless/media
  - paperless_export:/usr/src/paperless/export
  - paperless_consume:/usr/src/paperless/consume
  environment:
    PAPERLESS_REDIS: redis://redis:6379
    PAPERLESS_DBNAME: paperless
    PAPERLESS_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    PAPERLESS_ADMIN_MAIL: admin@example.com
    PAPERLESS_TASK_WORKERS: '2'
    PAPERLESS_ADMIN_USER: admin
    PAPERLESS_ENABLE_COMPRESSION: 'true'
    PAPERLESS_DBPASS: ${DB_PASSWORD}
    PAPERLESS_DBUSER: paperless
    PAPERLESS_SECRET_KEY: ${SECRET_KEY}
    PAPERLESS_DBHOST: paperless_db
    PAPERLESS_TASK_WORKERS_BACKUP: '1'
  command: null
  healthcheck: null
services:
- name: paperless_db
  image: postgres:16-alpine
  ports:
  - 127.0.0.1:5432:5432
  environment:
    POSTGRES_USER: paperless
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_DB: paperless
    POSTGRES_INITDB_ARGS: -c max_wal_level=replica
  volumes:
  - paperless_db:/var/lib/postgresql/data
  depends_on: []
  command: null
  healthcheck:
    test: CMD-SHELL pg_isready -U paperless -d paperless
    interval: 10s
    timeout: 5s
    retries: 10
- name: redis
  image: redis:7-alpine
  ports:
  - 127.0.0.1:6379:6379
  environment: {}
  volumes:
  - paperless_redis:/data
  depends_on: []
  command: null
  healthcheck:
    test: CMD redis-cli ping
    interval: 10s
    timeout: 5s
    retries: 10
proxy:
  type: none
  auto_detect: false
  domains: []
  config: null
deploy:
  target: server
  environment: null
  compose_file: null
  deployment_hash: null
  cloud:
    provider: hetzner
    orchestrator: remote
    region: fsn1
    size: cpx22
    install_image: null
    remote_payload_file: null
    ssh_key: null
    key: null
    server: null
    public_ports:
    - '8000'
  server:
    host: 46.224.127.228
    user: root
    ssh_key: ${BASE_PATH}/stacker-project-test
    port: 22
  registry: null
  default_target: null
  targets: {}
install:
  inputs:
    commonDomain: paperless.example.com
environments: {}
ai:
  enabled: false
  provider: openai
  model: null
  api_key: null
  endpoint: null
  timeout: 0
  tasks: []
monitoring:
  status_panel: true
  healthcheck: null
  metrics: null
hooks:
  pre_build: ./scripts/generate-secrets.sh
  post_deploy: null
  on_failure: null
env_file: .env
env: {}
config_contract:
  services: {}
