services:
  app:
    build:
      context: ..
      dockerfile: .stacker/Dockerfile
    ports:
    - 9000:9000
    - 9001:9001
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
      RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: '*'
      RUSTFS_CONSOLE_ENABLE: 'true'
      RUSTFS_OBS_LOGGER_LEVEL: info
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_UNSAFE_BYPASS_DISK_CHECK: 'true'
      RUSTFS_VOLUMES: /data/rustfs0 /data/rustfs1 /data/rustfs2 /data/rustfs3
    volumes:
    - rustfs_data:/data
    - rustfs_logs:/app/logs
    restart: unless-stopped
    networks:
    - app-network
    labels:
      my.stacker.dns: app
      my.stacker.scope: project
      my.stacker.service: app
  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
    - 4318:4318
    restart: unless-stopped
    networks:
    - app-network
    labels:
      my.stacker.dns: otel-collector
      my.stacker.scope: project
      my.stacker.service: otel-collector
networks:
  app-network:
    driver: bridge
volumes:
  rustfs_data: null
  rustfs_logs: null
