services:
  app:
    image: outlinewiki/outline:latest
    ports:
      - "3000:3000"
    environment:
      COLLABORATION_URL: "http://localhost:3000"
      DATABASE_URL: "postgres://outline:feefc0ed1d00edd3bde295de38ee0f6ab572c2716a7016242893b00aa4b31b32@postgres:5432/outline?sslmode=disable"
      FILE_STORAGE_LOCAL_ROOT_DIR: "/var/lib/outline/data"
      FORCE_HTTPS: "false"
      NODE_ENV: "production"
      PORT: "3000"
      REDIS_URL: "redis://redis:6379"
      SECRET_KEY: "b83a850e209eac1ae45034486e3103de72f4647e12d544f341e1bd08d8afc86b"
      URL: "http://localhost:3000"
      UTILS_SECRET: "6053f6b4d20fe37f6b5587c70e78764ff36d176400f9b52a772ef5f57fadd68e"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "app"
      my.stacker.scope: "project"
      my.stacker.service: "app"

  postgres:
    image: postgres:16
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: "outline"
      POSTGRES_PASSWORD: "feefc0ed1d00edd3bde295de38ee0f6ab572c2716a7016242893b00aa4b31b32"
      POSTGRES_USER: "outline"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "postgres"
      my.stacker.scope: "project"
      my.stacker.service: "postgres"

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6380:6379"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "redis"
      my.stacker.scope: "project"
      my.stacker.service: "redis"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

