name: gitea
version: 1.21.0
organization: null
project:
  identity: gitea
app:
  type: custom
  path: .
  dockerfile: null
  image: gitea/gitea:latest
  build: null
  ports:
  - 3000:3000
  - 2222:22
  volumes:
  - gitea_data:/data
  environment:
    GITEA_SERVER_ROOT_URL: https://git.example.com/
    GITEA_RUN_MODE: prod
    GITEA_DATABASE_HOST: gitea_db:5432
    GITEA_DATABASE_NAME: gitea
    GITEA_DATABASE_USER: gitea
    GITEA_SERVER_HTTP_PORT: '3000'
    GITEA_SERVER_DOMAIN: git.example.com
    GITEA_SECURITY_INTERNAL_TOKEN: ${INTERNAL_TOKEN}
    GITEA_SERVER_SSH_PORT: '2222'
    GITEA_DATABASE_TYPE: postgres
    GITEA_DATABASE_PASSWD: ${DB_PASSWORD}
    GITEA_SECURITY_SECRET_KEY: ${SECRET_KEY}
  command: null
  healthcheck: null
services:
- name: gitea_db
  image: postgres:16-alpine
  ports:
  - 127.0.0.1:5432:5432
  environment:
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_DB: gitea
    POSTGRES_USER: gitea
  volumes:
  - gitea_db:/var/lib/postgresql/data
  depends_on: []
  command: null
  healthcheck:
    test: CMD-SHELL pg_isready -U gitea -d gitea
    interval: 10s
    timeout: 5s
    retries: 10
proxy:
  type: none
  auto_detect: false
  domains: []
  config: null
deploy:
  target: server
  environment: null
  compose_file: null
  deployment_hash: null
  cloud:
    provider: hetzner
    orchestrator: remote
    region: fsn1
    size: cpx22
    install_image: null
    remote_payload_file: null
    ssh_key: null
    key: null
    server: null
    public_ports:
    - '3000'
    - '2222'
  server:
    host: 46.224.127.228
    user: root
    ssh_key: /Users/vasilipascal/work/stacker-project-examples/stacker-project-test
    port: 22
  registry: null
  default_target: null
  targets: {}
install:
  inputs:
    commonDomain: git.example.com
environments: {}
ai:
  enabled: false
  provider: openai
  model: null
  api_key: null
  endpoint: null
  timeout: 0
  tasks: []
monitoring:
  status_panel: true
  healthcheck: null
  metrics: null
hooks:
  pre_build: ./scripts/generate-secrets.sh
  post_deploy: null
  on_failure: null
env_file: .env
env: {}
config_contract:
  services: {}
