services:
  app:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      APP_SECRET: "ef833eb5314cf8f8d61febc4eeb78db39467d5c8a21ca7d1f2a8440f88116cd4"
      DATABASE_URL: "postgresql://umami:19b8a93d475f4588acdb2100818ad2ca@postgres:5432/umami"
      HOSTNAME: "0.0.0.0"
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: "production"
      PORT: "3000"
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "app"
      my.stacker.scope: "project"
      my.stacker.service: "app"

  postgres:
    image: postgres:15-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: "umami"
      POSTGRES_PASSWORD: "19b8a93d475f4588acdb2100818ad2ca"
      POSTGRES_USER: "umami"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: "CMD-SHELL pg_isready -U umami -d umami"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network
    labels:
      my.stacker.dns: "postgres"
      my.stacker.scope: "project"
      my.stacker.service: "postgres"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

