name: onetimesecret

project:
  identity: onetimesecret

app:
  type: custom
  image: onetimesecret/onetimesecret:latest
  ports:
    - "3000:3000"
  environment:
    REDIS_URL: redis://onetimesecret-redis:6379
    HOSTNAME: localhost
    SECRET: ${SECRET}
  volumes:
    - ots_data:/var/lib/onetimesecret

services:
  - name: onetimesecret-redis
    image: redis:7-alpine
    volumes:
      - ots_redis:/data
    healthcheck:
      test: CMD redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  ots_data: {}
  ots_redis: {}

proxy:
  type: caddy
  auto_detect: false
  domains:
    - domain: onetimesecret.example.com
      ssl: off
      upstream: app:3000

hooks:
  pre_build: ./scripts/generate-secrets.sh

monitoring:
  status_panel: true

deploy:
  target: cloud
  cloud:
    provider: hetzner
    region: fsn1
    size: cpx22
    ssh_key: ${BASE_PATH}/stacker-project-test
    public_ports:
      - "80"
      - "443"
      - "3000"

env_file: .env
